# used to create registry
version: "3.8"
services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./.data/registry:/var/lib/registry
    restart: "no"
